name: copy_with_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  copy_with:
    git:
      url: https://gitlab.com/nkming2/dart-copy-with
      path: copy_with

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  copy_with_build:
    git:
      url: https://gitlab.com/nkming2/dart-copy-with
      path: copy_with_build

dependency_overrides:
  copy_with:
    path: ../../copy_with
  copy_with_build:
    path: ../
