name: copy_with_build
description: Generate copyWith()
version: 1.7.0
homepage: https://github.com/nkming2/dart-copy-with
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: '>=4.0.0'
  build: ^2.3.1
  collection: '>=1.15.0 <2.0.0'
  copy_with:
    git:
      url: https://github.com/nkming2/dart-copy-with
      path: copy_with
      ref: copy_with-1.3.0
  source_gen: ^1.2.6

dev_dependencies:
  build_test: ^2.1.5
  lints: ^2.0.0
  path: ^1.8.3
  test: ^1.16.0
