name: copy_with_build
description: Generate copyWith()
version: 1.8.1
homepage: https://github.com/nkming2/dart-copy-with
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  analyzer: '>=6.0.0'
  build: ">=2.3.1 <2.5.0"
  collection: '>=1.15.0 <2.0.0'
  copy_with:
    git:
      url: https://github.com/nkming2/dart-copy-with.git
      path: copy_with
      ref: copy_with-1.4.0
  source_gen: ^2.0.0

dev_dependencies:
  build_test: ">=2.1.5 <3.0.0"
  lints: ">=2.0.0"
  path: any
  test: any

dependency_overrides:
  copy_with:
    path: ../copy_with
